log4j.rootLogger=debug,stdout
log4j.logger.com.zaxxer.hikari=error
#log4j.rootLogger = stdout,D,E

#system output
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern = [%d{yyyy/MM/dd-HH:mm:ss}][%p][%C{1}.%M] %m%n
#log4j.appender.stdout.layout.ConversionPattern = [%c][%d{yyyy/MM/dd-HH:mm:ss}][%p][%C{1}.%M]\t->%m%n
log4j.appender.stdout.layout.ConversionPattern=[%5p][%25C{1}.%20M] %m%n
#file output1

#伺服器歷程
#log4j.appender.D = org.apache.log4j.DailyRollingFileAppender
#log4j.appender.D.File = ./log/info.log
#log4j.appender.D.Append = true
#log4j.appender.D.Threshold = INFO
#log4j.appender.D.layout=org.apache.log4j.PatternLayout
#log4j.appender.D.DatePattern='.'yyyy-MM-dd
#log4j.appender.D.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ]  %m%n
#file output2

#伺服器錯誤資訊
log4j.appender.E=org.apache.log4j.DailyRollingFileAppender
log4j.appender.E.File=./log/error.log
log4j.appender.E.Append=true
log4j.appender.E.Threshold=ERROR
log4j.appender.E.layout=org.apache.log4j.PatternLayout
log4j.appender.E.DatePattern='.'yyyy-MM-dd
log4j.appender.E.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ] %m%n